import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import Button from '../components/base/button'
import Card from "../components/base/card"

export default function Home () {
  return (
    <div>
      <Head>
        <title>Ge Sinau</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-3 border border-red-800 ">
        <div className="flex justify-end">
          <div className="w-24">
              <Link passHref href="/login">
                <Button>
                  <h2>Login</h2>
                </Button>
            </Link>
          </div>
        </div>
        <div className="mt-24 grid grid-cols-3 gap-16">
          <Card>
            <div>

                <Image 
                  src="/images/imm.png"
                  layout="fill"
                  objectFit="cover"
                  quality={100}
                  />
            </div>
          </Card>
          <Card>
            <div>

                <Image 
                  src="/images/imm.png"
                  layout="fill"
                  objectFit="cover"
                  quality={100}
                  />
            </div>
          </Card>
          <Card>
            <div>

                <Image 
                  src="/images/imm.png"
                  layout="fill"
                  objectFit="cover"
                  quality={100}
                  />
            </div>
          </Card>
        </div>
      </main>
    </div>
  )
}
